### ISSUE TITLE
Simplify migration

### ISSUE THREAD

**Issue by uschmann** [estate/bookshelf-paranoia#15]
Hi,

what do i need to put into my knex-mifgration to get soft-deletion to work.
The documentation didn´t made this clear to me.
Maybe i am missing something?

**Comment by bsiddiqui** [comment]
@uschmann all you have to do is run a migration to add whatever column you are using to track if the row has been soft deleted. 

As the readme suggests, the default column is `deleted_at` but you can override that with options when you're initializing the plugin.

You can see example migrations in the tests: https://github.com/estate/bookshelf-paranoia/blob/master/test/db/migrations/20160414202837_articles.js#L8

We didn't include the migration examples in the readme because it's a standard [knex](http://knexjs.org/) migration file, like you always use for bookshelf.

Let us know if you have any other questions!
