### ISSUE TITLE
Restore data soft deleted

### ISSUE THREAD

**Issue by kcauchy** [estate/bookshelf-paranoia#9]
I didn't find anything about a recovery for soft-deleted records. Is that considered in this project?

**Comment by bsiddiqui** [comment]
@kcauchy we haven't added anything for restoring a record yet. Since soft deleted records just have a deleted_at timestamp you could do something like this

```js
User.forge({ id: 1000 })
.fetch({ withDeleted: true })
.call('save', { deleted_at: null })
```

If we were to spend more time on something like that we'd probably add a restored_at timestamp as well so you could do this instead

```js
.call('save', { deleted_at: null, restored_at: new Date() })
```

If you're interested in this feature, we'd happily accept a PR

**Comment by kcauchy** [comment]
Besides, I think the configuration `{withDeleted: true}` is a little not so elegant for code readers.

There should be a function named `findWithDel` and `findOneWithDel` to be more specific and more elegant to read.

If a user has many options to set, he or she may prefer to use `{withDeleted: true}`, but, for a simple query operation, which happens in most scenarios, a simple sugar function is better.

Compare 
```javascript
User.findWithDel({email: 'example@example.com'});
```

to 
```
User.find({email: 'example@example.com'}, {withDeleted: true});
```

I think:
 * The first one is easier to read. 
 * When I misspell `withDeleted` in the options, I get no errors at all. But when I misspell a function, I get an error immediately.

**Comment by kcauchy** [comment]
Also, it can be something like this:

```javascript
User.withDel().find({ email: 'example@example.com' });
```

Which I don't know if it can be implemented in bookshelf.

**Comment by bsiddiqui** [comment]
@kcauchy not so sure about adding a class method like `.findWithDel` because I think that's a bit more opinionated and fairly easy to add yourself. This is meant to be an easy drop-in with bookshelf that uses all native methods. You get a lot more versatility when you can use the same `.fetch` or `.fetchAll` methods and just pass an option if you want to include deleted records. 

Using this approaching of passing an option makes it really easy for someone, like you, who prefers the class method to add a class method `.findWithDel` to there base model.

```js
findWithDel (query, option) {
  return this.forge(query).fetch(extend(options, { withDeleted: true })
}
```

As for a restore prototype method, I think that's a good idea. You don't need to add `restored_at`, I just thought it'd be nice to have. It should:
1. error if the model doesn't have soft deletes enabled
2. error if the model is not deleted
3. have tests
4. update documentation

Thanks so much for contributing!

**Comment by bsiddiqui** [comment]
@kcauchy going to close this now since it's been a while. Feel free to re-open if you're interested in adding this feature.
